### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by Metis77** [scdoshi/jquery-ajaxchimp#1]
This is really great.

is there a way, to get messages like errors back in your custom language?

For me it switches to the default english messages.

**Comment by scdoshi** [comment]
It seems that if you change the language setting for your list, the error messages should also be in your language? I'm curious to know if you have tried that already.

Source: https://groups.google.com/forum/#!topic/mailchimp-api-discuss/asu1NgXlbd0

**Comment by Metis77** [comment]
yes in the list settings a default language is set (german). 
All fields have the correct translated german values.

This Ajax Script writes the english version, anyway.

I implemented it here:
http://fgkh.de.91-250-83-113.hauptwolke.de/newsletter

**Comment by scdoshi** [comment]
OK. Thanks for the update. I'll look into it this weekend

**Comment by scdoshi** [comment]
I'm thinking the best way to tackle this is to have a js object with translations to all messages. Something like this:

```
translations = {
    de: {
        'Original english error': 'Translated german error'
    },
    fr: {
    }
}
```

We can then pass in an argument to the init function to display translated messages.

**Comment by thepixture** [comment]
Nice plugin.
I'm also looking for the language support and just want to know if this has already been implemented and how the code should look like.

Thanks

**Comment by scdoshi** [comment]
@thepixture Hasn't been implemented in the plugin yet.

As a stop-gap, it's easy enough to do in your javascript if you are only looking for one language.

Follow the pattern above. Have a javascript object that holds all the translations, and then use the callback to look up the returned string and replace it with the translated version.

**Comment by scdoshi** [comment]
I was going to add translations in, but on looking into it, it seems the plugin does not work anymore because mailchimp stopped allowing cross-domain requests. Please check your implementation and stop using the plugin if it does not work.

**Comment by Metis77** [comment]
still working for me:
http://fgkh.de.91-250-83-113.hauptwolke.de/newsletter

**Comment by scdoshi** [comment]
Oops! You are right.. it was a faulty plugin on my browsers that was causing the issue. Thanks for checking. I'm going to add in language support later today.

**Comment by scdoshi** [comment]
Version 1.1.0 add language support
