### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by ghost** [scdoshi/jquery-ajaxchimp#12]
Hi Sid,

I'm having problems getting this to work in IE9 or lower. Is this a known issue?

**Comment by scdoshi** [comment]
I haven't tested in IE, but there's nothing crazy going on, so I'd be
surprised if it didn't work.

At least IE8 and upwards should be fine.

Let me know what you find.

**Comment by heyfletch** [comment]
I was able to get this to work with IE8 & IE9 no problem.

I used in conjunction with https://github.com/parndt/jquery-html5-placeholder-shim, but not sure the placeholder is the issue you're having.

**Comment by thriveweb** [comment]
Thanks for the link Joe. I didn't know about that plugin! But it still wasn't working. I managed to track it down to line 52:

```
var label = form.find('label[for=' + email.attr('id') + ']');
```

It seems IE wasn't finding the Label element so I replaced it with a simple selector and it works fine now :)

```
var label = $('#mce_ajax');  
```
