### ISSUE TITLE
Request Method POST

### ISSUE THREAD

**Issue by nishantmodak** [scdoshi/jquery-ajaxchimp#13]
Somehow , the POST method isn't being used even after changing it to

```
 $.ajax({
                    type: "POST",
   ...
                 }
                });
```

The request is always GET. What am I missing?

**Comment by scdoshi** [comment]
Sorry, I'm not sure what you are talking about. Do you mean when the ajax request to mailchimp is made? Why do you need to do a POST request there? I'm not sure if mailchimp supports a POST request.

Without more information (request/response headers etc.), I can't really help here.

**Comment by scdoshi** [comment]
Closing as invalid. Please reopen if you add more relevant information.
