### ISSUE TITLE
some error messages aren't translated 

### ISSUE THREAD

**Issue by piermariacosina** [scdoshi/jquery-ajaxchimp#19]
the cause for this is that in some messages there is a part that varies based on what I've inputed 

"The username portion of the email address is invalid (the portion before the @: ùà)"

when this is tested againt the array of solutions && $.ajaxChimp.responses[msg]
returns always undefine 
i've made a workaround cutting the part of the message that change.
msg = msg.substring(0,msg.indexOf("(")-1);
so the message become something like 
"The username portion of the email address is invalid"

i think there is a better solution anyway

**Comment by scdoshi** [comment]
We can do this using regular expressions.

**Comment by boshtian** [comment]
I also came across this issue and I've solved it with a check if there is colon in msg, since the two messages who have the colon are the only ones which have the user input in response.

If you'd like I can make a pull request with my solution.

**Comment by scdoshi** [comment]
That would be great, thanks

**Comment by scdoshi** [comment]
will be solved in v2.0: https://github.com/scdoshi/jquery-ajaxchimp/pull/57
