### ISSUE TITLE
missing translation message 

### ISSUE THREAD

**Issue by piermariacosina** [scdoshi/jquery-ajaxchimp#20]
Too many subscribe attempts for this email address. Please try again in about 5 minutes.

this message is not translated, it should be added to the translation plugin and in the plugin itself

**Comment by scdoshi** [comment]
Hmm.. I tried to include as many as I could generate, but must have missed this one. If someone can reproduce this and get the EXACT copy of the error, I'll be happy to add it in.

Of course, Pull requests are even better

**Comment by Metis77** [comment]
what error number hast this message?

**Comment by scdoshi** [comment]
Covering this in v2.0. https://github.com/scdoshi/jquery-ajaxchimp/pull/57
