### ISSUE TITLE
Remove the 0 - from error messages.

### ISSUE THREAD

**Issue by paulallendotuk** [scdoshi/jquery-ajaxchimp#27]
Hey, thank you so much for this plugin, just what i needed.

I have one issue which i cannot solve.

When the form is submitted, the messages all display as expected and the email is submitted. The only issue is for error messages. All the error messages have " 0 - " at the beginning of the message.

Could you please advice how i can remove this.

Thanks again
Paul

**Comment by anamostafa** [comment]
Hello Paul.
Just Wonder How did you fix that ??
Thank you in advance.
