### ISSUE TITLE
CallBack function

### ISSUE THREAD

**Issue by sananes** [scdoshi/jquery-ajaxchimp#3]
Hey,

Thanks so much for the plugin, its great! Are there any other callbacks, for example I have:

```
function callbackFunction (resp) {

    if (resp.result === 'success') {
        alert("You have successfully subscribed!");
    } else if(resp.result === 'error') {
        alert("Error");
    }
}
```

But i'd like a processing and if say, the user is already subscribed. If you can help that will be very helpful, thank you! Appreciate the work you have put in!

**Comment by scdoshi** [comment]
Hi, Sorry, I don't exactly understand the question.

A callback is just a function that will be called when something asynchrounous is completed (an ajax request to mailchimp in this case).

**Comment by scdoshi** [comment]
It seems mailchimp stopped allowing cross-domain requests, so the plugin does not work anymore. Please double check you website if you were using it
