### ISSUE TITLE
Cant get translations to work

### ISSUE THREAD

**Issue by paulallendotuk** [scdoshi/jquery-ajaxchimp#33]
Hi, i have included the jquery.ajaxchimp.langs.js file below the main ajaxchimp file and initialised like so:

```
$('#mc-form').ajaxChimp({

    language: 'fr',

    callback: mailChimpResponse,
    url: 'my mailchimp URL'
});
function mailChimpResponse(resp) {

    if (resp.result === 'success') {
        $('.mailchimp-success').html('' + resp.msg).fadeIn(900);
        $('.mailchimp-error').fadeOut(400);

    } else if(resp.result === 'error') {
        $('.mailchimp-error').html('' + resp.msg).fadeIn(900);
    }  
}
```

But the error messages are not translating? They are still showing up in English.

Any assistance will be very welcome.

Thanks in advance.

**Comment by scdoshi** [comment]
If you are manually displaying the message via the callback, you have to pull the translations manually as well.

The resp object passed to the callback is the raw response recived from mailchimp, without any changes. The automatically translated message is displayed in the label for the email form element inside the form the plugin is activated on.

**Comment by anamostafa** [comment]
Hi Paul
I know it's long time but did you sucess doing that ? Appreciate your help
