### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by chrissun** [scdoshi/jquery-ajaxchimp#38]
After one email user submission (success or failure), the second submission (success or failure) does the following:
1.  Before the callback function is reached, the form <input> and <label> disappear.
2.  The callback function is reached with a failure and a "blank was inputted" error message.

Anybody else seen this?  Or am nuts..  FYI, im using the default implementation reconmended

**Comment by scdoshi** [comment]
Closing old issue from 2014.
