### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by genuino2** [scdoshi/jquery-ajaxchimp#40]
I've added the code

```
<script type="application/javascript" src="https://raw.githubusercontent.com/scdoshi/jquery-ajaxchimp/master/jquery.ajaxchimp.js"></script>
        <script>
        $('#mc-embedded-subscribe-form').ajaxChimp({
            url:'MYURL in right format'
        });
        </script>
```

But don't work. if i click on submit button a new window with mailchimop form will open.
where's the mistake?

**Comment by fabe** [comment]
I think you are not allowed to use GitHub as a CDN. Try hosting jquery.ajaxchimp.js yourself, it should work then.
