### ISSUE TITLE
First and Last Names

### ISSUE THREAD

**Issue by kjbenk** [scdoshi/jquery-ajaxchimp#41]
I am trying to use your form and also add first and last names.  I got the email to save properly and users are able to signup to my List which is great, but what if I wanted to get their first and last names.

I have already tried to add these fields with no luck:

`<input id="first_name" name="FNAME" type="text"  placeholder="First Name"/>`
`<input id="last_name" name="LNAME" type="text"  placeholder="Last Name"/>`

Any Advice

**Comment by kjbenk** [comment]
I just happened to figure out the problem.

I see that you are searching for all inputs of type "text" and changing their name attr to "EMAIL".  I don't know why you are doing this because it is causing this:

`<input id="first_name" name="FNAME" type="text" placeholder="First Name"/>`
`<input id="last_name" name="LNAME" type="text" placeholder="Last Name"/>`

to turn to this upon load:

`<input id="first_name" name="EMAIL" type="text" placeholder="First Name"/>`
`<input id="last_name" name="EMAIL" type="text" placeholder="Last Name"/>`

What I did to fix this was comment out this line `email.attr('name', 'EMAIL');`.  The only catch is that you must use "EMAIL" as the name for your email input field.

Great job otherwise :)

**Comment by dylanh724** [comment]
Bump - this is a workaround, not a fix - this should be fixed

**Comment by daniel-lanciana** [comment]
Forked the project to add support for first and last names: https://github.com/daniel-lanciana/ajaxchimp-english-only

_Note: Also stripped out translations as only using for English-speakers._
