### ISSUE TITLE
Where do I get my mailchimp post url?

### ISSUE THREAD

**Issue by insanity54** [scdoshi/jquery-ajaxchimp#44]
From README.md: 

"
The mailchimp post url will look like this:

```
http://blahblah.us1.list-manage.com/subscribe/post?u=5afsdhfuhdsiufdba6f8802&id=4djhfdsh99f
```

"

Where do I get my mailchimp post URL?

**Comment by insanity54** [comment]
The URL can be found on the mailchimp admin interface.

In the admin interface, first create a list. Something like, "Mycompany Newsletter". After creating a list, you will be given the option to create an embedded sign up form. The admin interface will give you some html to paste into your site. In that html you will find the url under the div #mc_embed_signup.

**Comment by maxmumford** [comment]
This should be added to the readme

**Comment by erickpiloto** [comment]
You save the day!
