### ISSUE TITLE
ajaxChimp function undefined

### ISSUE THREAD

**Issue by bpeterson1991** [scdoshi/jquery-ajaxchimp#50]
Hi there,

My plugin is not working because it's saying the function is undefined. I have the js script above where I call:

```
    <script type="text/javascript">
    $('#mc-embedded-subscribe-form').ajaxChimp({
        url: 'MYURL'
    });
</script>
```

Not sure why it's going undefined?

**Comment by ghost** [comment]
@enlatis how do you calling your scripts (order)?

Call jQuery first, then ajaxchimp and then your custom script. Also make sure that your ID match with the one you use.

**Comment by scdoshi** [comment]
Closing old issue.
