### ISSUE TITLE
Submitting Additional Fields

### ISSUE THREAD

**Issue by dillonbailey** [scdoshi/jquery-ajaxchimp#58]
Is it possible to submit additional fields beyond just "email" using AjaxChimp?

Regards,
Dillon

**Comment by kalinichenko88** [comment]
+

**Comment by i3inary** [comment]
Also trying to submit a hidden field.

**Comment by scdoshi** [comment]
The plugin just calls submit() on the form. If the form has additional fields, those should be submitted as well.
