### ISSUE TITLE
Not working over SSL

### ISSUE THREAD

**Issue by dmjio** [scdoshi/jquery-ajaxchimp#6]
Getting this error when trying to run the script over a secure connection.

``` javascript
[blocked] The page at 'http://blaaah.com' was loaded over HTTPS, 
but ran insecure content from 
'http://mylist.us3.list-manage1.com/subscribe/post-json?
u=04f8c1cd24075695174280554_1393032436879&
EMAIL=email%40gmail.com&_=1393032436880': 
this content should also be loaded over HTTPS.
```

When I try to prefix with `https` it also fails, and says it was trying to submit a GET request, which seems strange.

**Comment by scdoshi** [comment]
It seems mailchimp doesn't support https submissions from embedded forms.

See here:
http://kb.mailchimp.com/article/how-can-i-add-my-signup-form-on-my-website/#https

If you are running SSL on the page, the best option may be to post the data to your server, and then make a backend API call,,,

**Comment by dmjio** [comment]
That seems strange, I wonder what's the reasoning behind that.

**Comment by i3inary** [comment]
I was able to just change the submission URL to **https**://mylist.us3.list-manage1.com...etc

**Comment by dmjio** [comment]
@i3inary, maybe they changed it? can you paste your code?

**Comment by i3inary** [comment]
```
$('#region-signup-form').ajaxChimp({
    url: 'https://mylist.us3.list-manage.com/subscribe/post?u=af7e4.......a03&amp;id=2b.....7c'
});
```

**Comment by jprichardson** [comment]
I tried changing mine to `https` and I just get `net::ERR_INSECURE_RESPONSE` with Chrome 38. Also, according to http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website#https it seems like they support `https`. So maybe I'm doing something incorrectly, any thoughts?

**Comment by jprichardson** [comment]
Also, looks like it may have worked without error for @i3inary because there is no `callback` parameter. But I'm not sure that the subscription actually happened?

**Comment by jprichardson** [comment]
OK, I figured it out as well. You can see the difference between @i3inary posts. Essentially, make sure that the domain is **YOURLIST.us8.list-manage.com** and not **YOURLIST.coinbolt.us8.list-manage1.com** (without the `1`) and obviously with the `https`.

(sorry if you feel that I spammed this, hopefully it'll help someone else coming along). Maybe update the docs?

**Comment by joshreisner** [comment]
@jprichardson helped me and I wasn't even using the plugin. I was getting ERR_INSECURE_RESPONSE on a homegrown AJAX script for a Shopify theme. Removing the 1 fixed it for me. Appreciate it.
