### ISSUE TITLE
Error at responses

### ISSUE THREAD

**Issue by EugeneVdovenko** [scdoshi/jquery-ajaxchimp#62]
You have an small error with response for mailchimp. In your code

```
  'The domain portion of the email address is invalid (the portion after the @: )'    : 3,
```

and answer from mailchimp

```
 'The domain portion of the email address is invalid (the portion after the @: mail)'    : 3,
```

and translates don't work for 3rd variant.

**Comment by scdoshi** [comment]
This should be addressed in the 2.0 branch. Please try it out and see if it works for you.
